name: Lint

on:
  push:
    branches:
      - main
      
jobs:
  all:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get dependencies
        run: sudo apt-get update && sudo apt-get install gcc libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout 3m0s
